
@echo off
echo [GVVA] Starting System...
echo [GVVA] 1. Launching Python Core (Localhost:8000)...
start "GVVA Python Engine" cmd /k "cd python-core && python main.py"

echo [GVVA] 2. Launching Web Dashboard (Localhost:3000)...
echo [GVVA] Please wait...
cd c:\autokim
npm run dev
